name: Build dev branch

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-dev

jobs:
  pre-release:
    name: Build and pre-release by dev branch
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ windows-latest, macos-latest, ubuntu-latest ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
      
    permissions:
      contents: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
    
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
        
      - name: Build electron apps for windows platform
        if: matrix.os == 'windows-latest'
        run: npm run build:win32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build electron apps for darwin platform
        if: matrix.os == 'macos-latest'
        run: npm run build:darwin:x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build electron apps for linux platform
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux:x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.os }}
          path: release
          
      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/**"
          prerelease: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}